version: 0.9.{build}
 
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
platform: Any CPU
 
configuration: Release
 
build:
  project: RandomUser.sln
  verbosity: detailed
  publish_nuget: true
 
before_build:
  - nuget restore
 
nuget:
  account_feed: true
  project_feed: true
 
deploy:
  provider: NuGet
  api_key:
    secure: gOlh/RDly+iLvoIpSUjYyaPAPP5nxyysOx9+inBZICcnj7fVC7UlXze8qwMhzono
  skip_symbols: false
  artifact: /.*\.nupkg/